# chtc_hyde.sub

universe = vanilla
log = job_$(Cluster).log
error = job_$(Cluster)_$(Process).err
output = job_$(Cluster)_$(Process).out

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
executable = run_HyDe.sh
transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/bjorner/HyDe.tar.gz, run_hyde.py, $(Process)_seqgen.out, n10h2map.txt
arguments = $(Process)_seqgen.out n10h2map.txt 10


request_cpus = 1
request_memory = 2GB
request_disk = 2GB

queue 10