# phylo.sub
# starter submit file for CHTC jobs

universe = vanilla

tempProcess = $(Process) + 1
newProcess = $INT(tempProcess)

log = job_$(Cluster).log
error = job_$(Cluster)_$(newProcess).err
output = job_$(Cluster)_$(newProcess).out

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

executable = chtc_phylo.sh
# inputs
map=n10h2map.txt
true_net=n10.net

transfer_input_files = $(newProcess)_astral.in, julia-1.6.1-linux-x86_64.tar.gz,\
    my-project-julia.tar.gz, chtc_TICR.jl, http://proxy.chtc.wisc.edu/SQUID/chtc/R402.tar.gz,\
    packages.tar.gz, chtc_MSCquartets.R, http://proxy.chtc.wisc.edu/SQUID/bjorner/HyDe.tar.gz,\
    run_hyde.py, $(map), Seq-Gen-1.3.4.tar.gz, $(true_net), TICR.tar.gz, chtc_cfTable.jl, find-cut-Linux-64,\
    chtc_expected_cfTable.jl, chtc_HyDe_table.jl, chtc_TICRMSC_table.jl
arguments = $(newProcess)_astral.in $(map) 10 30 $(true_net) $(newProcess)

request_cpus = 1
request_memory = 8GB
request_disk = 8GB

queue 1