# phylo.sub
# starter submit file for CHTC jobs

universe = vanilla

#tempProcess = $(Process) + 1
#newProcess = $INT(tempProcess)

### inputs
num_taxa=25
map_name=n25h5map.txt
true_net=n25h5.net
folder_name=n25h5

log = logs/job_$(Cluster)_$(true_net)_$(num_trees).log
error = logs/job_$(Cluster)_$(newProcess).err
output = logs/job_$(Cluster)_$(newProcess).out

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

executable = chtc_phylo.sh

# singleNet/n15orange/n15orange-gt$(num_trees)-$(newProcess)-1.tre
# all_hybs/n$(network)_n$(num_trees)/$(newProcess)_astral.in
# input/all_hybs/n$(network)_n$(num_trees)/$(newProcess)_astral.in

transfer_input_files = output/, nets_newick/$(true_net), directory/$(folder_name).txt, directory/n25seq.txt, maps_hyde/$(map_name), input/$(folder_name)/$(process), julia-1.6.1-linux-x86_64.tar.gz,\
    my-project-julia.tar.gz, chtc_TICR.jl, http://proxy.chtc.wisc.edu/SQUID/chtc/R402.tar.gz,\
    packages.tar.gz, chtc_MSCquartets.R, http://proxy.chtc.wisc.edu/SQUID/bjorner/HyDe.tar.gz,\
    run_hyde.py, Seq-Gen-1.3.4.tar.gz, TICR.tar.gz, chtc_cfTable.jl, find-cut-Linux-64,\
    d1_d2.py, D3_D_combinations.py, \
    chtc_expected_cfTable.jl, chtc_HyDe_Dstat_table.jl, chtc_TICRMSC_table.jl, seqgen2hyde.py

### arguments: input file, map, network,    e.g. n15orange-gt$(num_trees)-$(newProcess)-1.tre, $(newProcess)_astral.in
arguments = $(process) $(map_name) $(num_taxa) $(true_net)

# need for cpus, disk, and memory changes based on the size of the network and
# number of gene trees used. Typically, larger networks wtih more than 3000 gene trees require more
# memory and disk space

request_cpus = 1
request_memory = 8GB
request_disk = 8GB

# number to run

####### QUEUE PROCESSES FROM NUMBER OR TEXT FILE
# queue 30

queue process from directory/n25seq.txt