# phylo.sub
# starter submit file for CHTC jobs

universe = vanilla

tempProcess = $(Process) + 1
newProcess = $INT(tempProcess)


### inputs

    # network
    network=6

    # map is either n10h2map.txt, n15h3map.txt, n25h5map.txt, or n50h10map.txt
    map=n6h1map.txt

    # true net is either: n10.net, n15.net, n25h5_1.net, 50h10_1.net, n10orange_1.net n15blue.net, n15red.net, n15orange.net
    true_net=n6.net

    num_trees=1000

log = logs/job_$(Cluster)_$(true_net)_$(num_trees).log
error = logs/job_$(Cluster)_$(newProcess).err
output = logs/job_$(Cluster)_$(newProcess).out

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

executable = chtc_phylo.sh

# singleNet/n15orange/n15orange-gt$(num_trees)-$(newProcess)-1.tre
# all_hybs/n$(network)_n$(num_trees)/$(newProcess)_astral.in

transfer_input_files = output/, input/all_hybs/n$(network)_n$(num_trees)/$(newProcess)_astral.in, julia-1.6.1-linux-x86_64.tar.gz,\
    my-project-julia.tar.gz, chtc_TICR.jl, http://proxy.chtc.wisc.edu/SQUID/chtc/R402.tar.gz,\
    packages.tar.gz, chtc_MSCquartets.R, http://proxy.chtc.wisc.edu/SQUID/bjorner/HyDe.tar.gz,\
    run_hyde.py, $(map), Seq-Gen-1.3.4.tar.gz, $(true_net), TICR.tar.gz, chtc_cfTable.jl, find-cut-Linux-64,\
    chtc_expected_cfTable.jl, chtc_HyDe_Dstat_table.jl, chtc_TICRMSC_table.jl, seqgen2hyde.py

### arguments: input file, map, network,    e.g. n15orange-gt$(num_trees)-$(newProcess)-1.tre
arguments = $(newProcess)_astral.in $(map) $(network) $(num_trees) $(true_net) $(newProcess) 

# $(seq_length)

# need for cpus, disk, and memory changes

#request_cpus = 2
# trees >3000 require more memory and disk space; 16gb too low, 32gb too low for 3000.
#request_memory = 64GB
#request_disk = 64GB

request_cpus = 1
request_memory = 16GB
request_disk = 16GB

# number to run
queue 1