# julia-job.sub

universe = vanilla

log = job_$(Cluster).log
error = job_$(Cluster)_$(Process).err
output = job_$(Cluster)_$(Process).out

executable = run_TICR.sh

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = julia-1.6.1-linux-x86_64.tar.gz, my-project-julia.tar.gz, chtc_TICR.jl, $(Process)_astral.in, $(Process)_astral.QMC.tre
arguments = $(Process)_astral.in $(Process)_astral.QMC.tre

request_cpus = 2
request_memory = 4GB
request_disk = 4GB

queue 10