# phylo.sub
# starter submit file for CHTC jobs

universe = vanilla
log = job_$(Cluster).log
error = job_$(Cluster)_$(Process).err
output = job_$(Cluster)_$(Process).out

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
executable = run_MSCquartets.sh
transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/chtc/R402.tar.gz, packages.tar.gz, chtc_MSCquartets.R, $(Process)_astral.in
arguments = $(Process)_astral.in


request_cpus = 1
request_memory = 1GB
request_disk = 1GB

queue 10